# Site settings
title: anna scaife
author: Anna Scaife
name: as595
email: anna.scaife@manchester.ac.uk
logo: /assets/img/anna_scaife_nature.jpeg

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Artificial intelligence for Astrophysics. Mainly deep-learning. Foundation models, 
  Bayesian-ness, data-driven. Fuelled by coffee and sourdough. 
  Current cocktail of choice: Manhattan. 

# Build settings:
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  - { platform: github,         user_url: "https://github.com/as595" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/anna-scaife-manchester" }
  - { platform: twitter,        user_url: "https://twitter.com/radastrat" }

header_pages:
  - publications.md
  - research.md
  - teaching.md
  - writing.md
  - consultancy.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
